app/produit/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_wtf.html5 import URLField
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length,Email, EqualTo, ValidationError, url
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import Types, Categorie

def rech_cate():
    return Categorie.query.filter_by(statut=True)

class AjoutProForm(FlaskForm):
    nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    prix_p= DecimalField('Prix', validators=[DataRequired("Le prix du produit")])
    img_url=URLField('URL')
    rech_cate= QuerySelectField(query_factory=rech_cate, get_label='nom', allow_blank=False)
    submit = SubmitField('Produit')

class AjoutPhoForm(FlaskForm):
    file = FileField("Image",validators=[FileAllowed(['jpg','png'],'Seul jpg et png sont autorisés')])
    submit = SubmitField('Produit')

class EdProForm(FlaskForm):
    ed_nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    ed_prix_p= DecimalField('Prix', validators=[DataRequired("Le prix du produit")])
    ed_img_url=URLField('URL')
    ed_rech_cate= QuerySelectField(query_factory=rech_cate, get_label='nom', allow_blank=False)
    submit = SubmitField('Produit')

class EdPhoForm(FlaskForm):
    ed_file = FileField("Image",validators=[FileAllowed(['jpg','png'],'Seul jpg et png sont autorisés')])
    submit = SubmitField('Produit')

app/produit/__init__.py
from flask import Blueprint

produit = Blueprint('produit', __name__, url_prefix='/produit')
# never forget 
from . import routes

app/produit/routes.py
from flask import render_template, flash, url_for, redirect, request, session
from .. import db, bcrypt
from ..models import Types, Categorie, Produit
from app.produit.forms import AjoutProForm, AjoutPhoForm, EdProForm,EdPhoForm
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy.sql import func
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url

from . import produit



''' Ajoute un produit '''

@produit.route('/ajout_produit', methods=['GET', 'POST'])
@login_required
def ajoutprod():

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Titre
   title='Produit | Kivu Exchange'
   #formulaire
   form=AjoutProForm()

   if form.validate_on_submit():
      nom_pro=form.nom.data.capitalize()
      #Requete de verification du produit
      req_ver=Produit.query.filter_by(nom=nom_pro, categorie_id=form.rech_cate.data.id).first()
      #Vérification.
      if req_ver is not None:
         flash("Ce produit existe",'success')
         return redirect(url_for('produit.ajoutprod')) 
      #Code du produit
      code_produit_une=db.session.query(func.max(Produit.id).label("idmax")).first()
      code_pro_systeme=""
      if code_produit_une.idmax is None:
         code_pro_systeme="#{}1".format(form.rech_cate.data.id)
      else:
         precede_prod=code_produit_une.idmax + 1
         if precede_prod < 10:
               precede_prod="{}{}".format(0,precede_prod)
               code_pro_systeme="#{}{}".format(form.rech_cate.data.id,precede_prod)
         else:
               code_pro_systeme="#{}{}".format(form.rech_cate.data.id,precede_prod)
      
      #Code unique
      code_produit=code_pro_systeme
      #Produit 
      if form.img_url.data=="":
         produit_enre=Produit(nom=nom_pro, categorie_id=form.rech_cate.data.id, prix_p=form.prix_p.data,user_produit=current_user, statut=False, code=code_produit)
         db.session.add(produit_enre)
         db.session.commit()
         flash("Charger l'image du produit maintenant!",'success')
         session['img']=code_produit
         return redirect(url_for('produit.upload_file'))
      else: 
         produit_enre=Produit(nom=nom_pro, categorie_id=form.rech_cate.data.id, prix_p=form.prix_p.data,user_produit=current_user, img_url=form.img_url.data, statut=False, code=code_produit)
         db.session.add(produit_enre)
         db.session.commit()
         flash("Ajout d'un nouveau produit",'success')
      return redirect(url_for('produit.lipro')) 

   return render_template('produit/ajpro.html',  title=title, form=form)

""" Liste des produits """

@produit.route('/lis_produit', methods=['GET', 'POST'])
@login_required
def lipro():
   
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))
   #Titre
   title='Produit | Kivu Exchange'
   #Requet des pagination et des listage des données
   page= request.args.get('page', 1, type=int)
   livre_page=Produit.query.order_by(Produit.id.desc()).paginate(page=page, per_page=50)
    
   return render_template('produit/views.html', title=title, liste=livre_page)


""" Upload l'image avec Cloudinary """

@produit.route('/img', methods=['GET', 'POST'])
def upload_file():
   
   #Titre
   title="Image | Kivu Exchanges"
   #Verification de session
   if 'img' in session:
      id_rech=session['img']
   else:
      return redirect(url_for('produit.ajoutprod')) 
   #Produit à modifier
   prod_img=Produit.query.filter_by(code=id_rech).first() 
   #Formualire
   form=AjoutPhoForm()
   upload_result = None
   if form.validate_on_submit():
      file_to_upload = form.file.data
      if file_to_upload:
         try:
            upload_result = upload(file_to_upload)
         except:
            flash("Erreur de connexion",'danger')
            session.pop('img',None)
            return redirect(url_for('produit.lipro')) 
            
         prod_img.img_url=upload_result['url']
         db.session.commit()
         flash("Ajout d'un nouveau produit",'success')
         session.pop('img',None)
         return redirect(url_for('produit.lipro')) 
   return render_template('produit/upload_form.html', form=form)


""" Modifier statut du produit"""

@produit.route('/statut_produit/<int:pro_id>', methods=['GET', 'POST'])
@login_required
def statutpro(pro_id):
   #Titre
   title='Produit | Kivu Exchanges'

   #verification de l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Requête de vérification de produit
   pro_statu=Produit.query.filter_by(id=pro_id).first()

   if pro_statu is None:
      return redirect(url_for('produit.lipro'))

   if pro_statu.statut == True:
      pro_statu.statut=False
      db.session.commit()
      flash("Le produit est activé sur la plateforme",'success')
      return redirect(url_for('produit.lipro'))
   else:
      pro_statu.statut=True
      db.session.commit()
      flash("Le produit est desactivé sur la plateforme",'success')
      return redirect(url_for('produit.lipro'))
   
   return render_template('user/views.html',title=title)


""" Modification du produit  """

@produit.route('/edit_<int:pro_id>_pro', methods=['GET', 'POST'])
@login_required
def editpro(pro_id):
       
   #Modification par l'administrateur
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))       
   
   form=EdProForm()
   #Titre
   title='Produit | Kivu Exchange'
   #Requête de vérification du type
   pro_class=Produit.query.filter_by(id=pro_id).first()
   #Le nom du type encours de modification
   pro_nom=pro_class.nom

   if pro_class is None:
      return redirect(url_for('produit.litcate'))
   
   if form.validate_on_submit():
      req_ver=Produit.query.filter_by(nom=form.ed_nom.data.capitalize(), categorie_id=form.ed_rech_cate.data.id).first()
      
      if req_ver is None:
         if form.ed_img_url.data=="":
            pro_class.nom=form.ed_nom.data.capitalize()
            pro_class.categorie_id=form.ed_rech_cate.data.id
            pro_class.prix_p=form.ed_prix_p.data
            db.session.commit()
            flash("Veuillez upload l'image",'success')
            session['img']=pro_id
            return redirect(url_for('produit.upload_file_ed', pro_id=pro_id))
         else:
            pro_class.nom=form.ed_nom.data.capitalize()
            pro_class.categorie_id=form.ed_rech_cate.data.id
            pro_class.prix_p=form.ed_prix_p.data
            pro_class.img_url=form.ed_img_url.data
            db.session.commit()
            flash("Modification réussie",'success')
            return redirect(url_for('produit.lipro'))
            
      else:
         if form.ed_img_url.data=="":
            pro_class.prix_p=form.ed_prix_p.data
            db.session.commit()
            flash("Veuillez upload l'image",'success')
            session['img']=pro_id
            return redirect(url_for('produit.upload_file_ed', pro_id=pro_id))
         else:
            pro_class.prix_p=form.ed_prix_p.data
            pro_class.img_url=form.ed_img_url.data
            db.session.commit()
            flash("Modification réussie",'success')
            return redirect(url_for('produit.litcate'))

   if request.method=='GET':
      form.ed_nom.data=pro_class.nom
      form.ed_rech_cate.data=pro_class.categorie_produit.nom
      form.ed_prix_p.data=pro_class.prix_p
      form.ed_img_url.data=pro_class.img_url

   return render_template('produit/editpro.html', form=form, title=title, pro_nom=pro_nom)


""" Upload l'image avec Cloudinary """

@produit.route('/imged<int:pro_id>', methods=['GET', 'POST'])
def upload_file_ed(pro_id):
   
   #Titre
   title="Image | Kivu Exchanges"
   #Verification de session
   if 'img' in session:
      id_rech=session['img']
   else:
      return redirect(url_for('produit.lipro')) 
   #Produit à modifier
   prod_img=Produit.query.filter_by(id=pro_id).first() 
   #Formualire
   form=EdPhoForm()
   upload_result = None
   if form.validate_on_submit():
      file_to_upload = form.ed_file.data
      if file_to_upload:
         try:
            upload_result = upload(file_to_upload)
         except:
            flash("Erreur de connexion",'danger')
            session.pop('img',None)
            return redirect(url_for('produit.lipro')) 
         prod_img.img_url=upload_result['url']
         db.session.commit()
         flash("Modification avec succès",'success')
         session.pop('img',None)
         return redirect(url_for('produit.lipro')) 
   return render_template('produit/upload_form_ed.html', form=form, title=title)

app/templates/produit/ajpro.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Ajouter produit</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
 
                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Nom du produit</label>
                                    {% if form.nom.errors %}
                                    {{ form.nom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.nom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.nom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Prix du produit($)</label>
                                    {% if form.prix_p.errors %}
                                    {{ form.prix_p(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.prix_p.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.prix_p(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                <label>Catégorisation</label>
                                {% if form.rech_cate.errors %}
                                {{ form.rech_cate(class="form-control select2 ")}}
                                <i class="form-group__bar"></i>
                                <div class="invalid-feedback">
                                    {% for error in form.rech_cate.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.rech_cate(class="form-control select2")}}
                                <i class="form-group__bar"></i>
                                {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Url image</label>
                                    {% if form.img_url.errors %}
                                    {{ form.img_url(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.img_url.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.img_url(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="text-center">
                        <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-view-list-alt"></i> Nouveau produit
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/produit/editpro.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Editer produit {{pro_nom}} </h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
 
                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Nom du produit</label>
                                    {% if form.ed_nom.errors %}
                                    {{ form.ed_nom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_nom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_nom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Prix du produit($)</label>
                                    {% if form.ed_prix_p.errors %}
                                    {{ form.ed_prix_p(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_prix_p.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_prix_p(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                <label>Catégorisation</label>
                                {% if form.ed_rech_cate.errors %}
                                {{ form.ed_rech_cate(class="form-control select2 ")}}
                                <i class="form-group__bar"></i>
                                <div class="invalid-feedback">
                                    {% for error in form.ed_rech_cate.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.ed_rech_cate(class="form-control select2")}}
                                <i class="form-group__bar"></i>
                                {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Url image</label>
                                    {% if form.ed_img_url.errors %}
                                    {{ form.ed_img_url(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_img_url.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_img_url(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="text-center">
                        <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-pencil-altr"></i> Editer produit
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/produit/upload_form.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="text-center title">Image du produit</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
 
                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label> <small>* image de produit</small> </label>
                                    {% if form.file.errors %}
                                    {{ form.file(class="file-control is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.file.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.file(class="file-control ")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-right">
                            <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                    <i class="ti-cloud"></i> Upload
                            </button>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </form>
        </div>
    </div>

 
</div>



{% endblock body %}

app/templates/produit/upload_form_ed.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="text-center title">Image à modifier</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
 
                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label> <small>* image de produit</small> </label>
                                    {% if form.ed_file.errors %}
                                    {{ form.ed_file(class="file-control is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_file.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_file(class="file-control ")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-right">
                            <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                    <i class="ti-cloud"></i> Upload
                            </button>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </form>
        </div>
    </div>

 
</div>



{% endblock body %}

app/templates/produit/views.html
{% extends "base.html" %}

{% block body %}

<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 80px 30px  80px">
            
        <div class="header">
            <h4 class="title">Les produits de l'entreprise</h4>
            <br>
            <a href="{{ url_for('produit.ajoutprod')}}" class="btn btn-primary"> <i class="ti-view-list-alt "></i> Ajouter produit </a>
        </div>
        <br>
       
        {% with messages= get_flashed_messages(with_categories=true) %}
            {% if messages  %}
                {% for category, message in messages %}
                    <div class="alert text-center alert-{{ category }}">
                        <b>{{ message }}</b>
                    </div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">

                <thead>
                    <th>Code</th>
                    <th>Avatar</th>
                    <th>Nom produit</th>
                    <th class="text-center">Prix</th>
                    <th  class="text-center">Catégorie</th>
                    <th  class="text-center">Classification</th>
                    <th  class="text-center">Statut</th>
                    <th  class="text-center">Action</th>
                </tr></thead>
                <tbody>
                    {% for listes in liste.items%}
                        <tr>
                            <td> {{ listes.code }} </td>
                            <td> <img height="60px" width="60px" class="img img-resposive img-circle box-shadow--5dp" src=" {{listes.img_url}} " alt="produit"> </td>
                            <td> {{ listes.nom }} </td>
                            <td class="text-center"> ${{ listes.prix_p }} </td>
                            <td  class="text-center"> {{ listes.categorie_produit.nom }} </td>
                            <td  class="text-center"> {{ listes.categorie_produit.type_categorie.nom }} </td>
                            {% if listes.statut==True%}
                            <td  class="text-center"><a href="{{ url_for('produit.statutpro', pro_id=listes.id)}}  " class="btn btn-success"> <i class="ti-unlock"></i> </a></td>
                            {% else %}
                            <td  class="text-center"><a href="{{ url_for('produit.statutpro', pro_id=listes.id)}}" class="btn btn-danger"> <i class="ti-lock"></i> </a></td>
                            {% endif%}
                            <td  class="text-center"> <a href="{{ url_for('produit.editpro', pro_id=listes.id)}}" class="btn btn-warning"> <i class="ti-pencil-alt"></i> </a> </td>
                        </tr>
                    {% endfor %}
 
                </tbody>
            </table>

            <div class="box-footer clearfix">
                <div class="text-center">
                    {% for page_num in liste.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                        {% if liste.page==page_num %}
                            <a class="btn btn-info mb-4" href="{{ url_for('produit.lipro', page=page_num) }}">{{ page_num}}</a>
                        {% else %}
                            <a class="btn btn-outline-info mb-4" href="{{ url_for('produit.lipro', page=page_num) }}">{{ page_num}}</a>
                        {% endif %}
                    {% else %}
                        ...
                    {% endif %}
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock body %}