app/user/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length,Email, EqualTo, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import User

def rech_user():
    return Service.query.filter_by(active=True)

class AjouteruserForm(FlaskForm):
    nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    post_nom= StringField('Post-nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    prenom= StringField('Prénom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    username= StringField('Email', validators=[DataRequired('Veuillez completer votre email'), Email('Votre email est incorrect')])
    password= PasswordField('Mot de passe', validators=[DataRequired('Veuillez completer votre mot de passe')])
    role= SelectField('Rôle',choices=[('Admin', 'Admin'), ('Webmaster', 'Webmaster')])
    submit = SubmitField('Créer compte')

    #Fornction de verification d'unique existenace dans la base des données
    def validate_username(self, username):
        user= User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("Cet utilisateur existe déjà")

class EditeruserForm(FlaskForm):
    ed_nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    ed_post_nom= StringField('Post-nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    ed_prenom= StringField('Prénom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    ed_username= StringField('Email', validators=[DataRequired('Veuillez completer votre email'), Email('Votre email est incorrect')])
    ed_role= SelectField('Rôle',choices=[('Admin', 'Admin'), ('Webmaster', 'Webmaster')])
    ed_submit = SubmitField('Créer compte')


class PassuserForm(FlaskForm):
    password= PasswordField('Mot de passe', validators=[DataRequired('Veuillez completer votre mot de passe')])
    confirm_password= PasswordField('Confirmer mot de passe', validators=[DataRequired('Veuillez completer votre mot de passe'), EqualTo('password',message="Les mots des passes ne pas conforment")])
    submit = SubmitField('Changer mot de passe')
    

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__, url_prefix='/utilisateur')
# never forget 
from . import routes

app/user/routes.py
from flask import render_template, flash, url_for, redirect, request, session
from .. import db, bcrypt
from ..models import User 
from app.user.forms import AjouteruserForm, PassuserForm, EditeruserForm
from flask_login import login_user, current_user, logout_user, login_required
from . import user


""" Ajout d'un nouveau user """

@user.route('/ajouteruti', methods=['GET', 'POST'])
@login_required
def ajuser():
   title='Utilisateur | Kivu Exchange'
    #Formulaire de service
   form=AjouteruserForm()
   #ENregfistrement des operations

   if form.validate_on_submit():
      nom=form.nom.data.upper()
      prenom=form.prenom.data.capitalize()
      post_nom=form.post_nom.data.upper()
      password_hash=bcrypt.generate_password_hash(form.password.data).decode('utf-8')   
      utilisateur=User(nom=nom, prenom=prenom,post_nom=post_nom, password=password_hash, username=form.username.data,role=form.role.data)
      db.session.add(utilisateur)
      db.session.commit()
      flash("Ajout d'un utilisateur avec succès",'success')
      return redirect(url_for('user.liuser')) 
   return render_template('user/ajuser.html', form=form, title=title)

#Administrateur
@user.route('/ajouteradmin', methods=['GET', 'POST'])
def ajouteruserad():
   title='Administrateur | Kivu Exchange'
    #Formulaire de service
   form=AjouteruserForm()
   #ENregfistrement des operations

   ## Vérification de l'existence d'au moins un administrateur
   ver_admini_existe= User.query.filter_by(statut=True, role="Admin").first()
   if ver_admini_existe is not None:
      return redirect(url_for('auth.logout'))

   if form.validate_on_submit():
      nom=form.nom.data.upper()
      prenom=form.prenom.data.capitalize()
      post_nom=form.post_nom.data.upper()
      password_hash=bcrypt.generate_password_hash(form.password.data).decode('utf-8')   
      utilisateur=User(nom=nom, prenom=prenom,post_nom=post_nom, statut=True, password=password_hash, username=form.username.data,role=form.role.data)
      db.session.add(utilisateur)
      db.session.commit()
      flash("Un administrateur est crée",'success')
      return redirect(url_for('auth.login')) 
   return render_template('user/ad.html', form=form, title=title)





   """ Liste utilisateur """

@user.route('/listeuti', methods=['GET', 'POST'])
@login_required
def liuser():
   #Titre
   title='Utilisateur | Kivu Exchange'
   #Requête d'affichage des utlisateurs
   listes=User.query.order_by(User.id.desc())

   return render_template('user/views.html',title=title, liste=listes)


""" Modifier statut de l'Utilisateur """

@user.route('/statutut/<int:user_id>', methods=['GET', 'POST'])
@login_required
def statutuser(user_id):
   #Titre
   title='Utilisateur | Kivu Exchange'
   #Requête de vérification de l'utilisateur
   user_statu=User.query.filter_by(id=user_id).first()

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))
   
   #La modification du mot de passe par l'administrateur.
   if current_user.id== user_statu.id:
      return redirect(url_for('user.liuser'))
   
   if user_statu is None:
      return redirect(url_for('user.liuser'))

   if user_statu.statut == True:
      user_statu.statut=False
      db.session.commit()
      flash("l'utilisateur est désactivé sur la plateforme",'success')
      return redirect(url_for('user.liuser')) 
   else:
      user_statu.statut=True
      flash("l'utilisateur est activé sur la plateforme",'success')
      db.session.commit()
      return redirect(url_for('user.liuser')) 
   
   return render_template('user/views.html',title=title)

""" Modifier le mot de passé de l'utilisateur """

@user.route('/motdepass/<int:user_id>', methods=['GET', 'POST'])
@login_required
def passuser(user_id):
   
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))
          
   form=PassuserForm()
   #Titre
   title='Utilisateur | Kivu Exchange'
   #Requête de vérification de l'utilisateur
   user_pass=User.query.filter_by(id=user_id).first()

   user_nom=user_pass.prenom

   if user_pass is None:
      return redirect(url_for('user.liuser'))

   if form.validate_on_submit():
      password_hash=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user_pass.password=password_hash
      db.session.commit()
      return redirect(url_for('auth.logout')) 

   return render_template('user/password.html', form=form, title=title, user_nom=user_nom)


""" Modification des informations de l'utilisateur """

@user.route('/editut_<int:user_id>', methods=['GET', 'POST'])
@login_required
def edituser(user_id):
       
   form=EditeruserForm()
   #Titre
   title='Utilisateur | Kivu Exchange'
   #Requête de vérification de l'utilisateur
   user_pass=User.query.filter_by(id=user_id).first()
   #Le nom de l'utilisateur en cours de modification
   user_nom=user_pass.prenom

   if user_pass is None:
      redirect(url_for('user.liuser'))
   
   #La modification des informations de l'utilisateur.
   if current_user.id is not user_pass.id:
      return redirect(url_for('main.dashboard'))

   if form.validate_on_submit():
      if form.ed_username.data == user_pass.username:
         user_pass.nom=form.ed_nom.data.upper()
         user_pass.post_nom=form.ed_post_nom.data.upper()
         user_pass.prenom=form.ed_prenom.data.capitalize()
         user_pass.role=form.ed_role.data
         db.session.commit()
         flash("Modification réussie",'success')
         return redirect(url_for('user.liuser')) 
      user_pass.nom=form.ed_nom.data.upper()
      user_pass.post_nom=form.ed_post_nom.data.upper()
      user_pass.prenom=form.ed_prenom.data.capitalize()
      user_pass.role=form.ed_role.data
      user_pass.username=form.ed_username.data
      db.session.commit()
      flash("Modification réussie",'success')
      return redirect(url_for('user.liuser')) 
   
   if request.method=='GET':
      form.ed_nom.data=user_pass.nom
      form.ed_post_nom.data=user_pass.post_nom
      form.ed_prenom.data=user_pass.prenom
      form.ed_role.data=user_pass.role
      form.ed_username.data=user_pass.username

   return render_template('user/edituser.html', form=form, title=title, user_nom=user_nom)

app/templates/user/ad.html
{% extends "basead.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Ajouter utilisateur</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
                <div class="row">
                    <div class="col-md-4">
                            <div class="form-group">
                                    <label>Prénom</label>
                                    {% if form.prenom.errors %}
                                    {{ form.prenom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.prenom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.prenom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
                    <div class="col-md-8">
                            <div class="form-group">
                                    <label>Nom </label>
                                    {% if form.nom.errors %}
                                    {{ form.nom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.nom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.nom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="row">
                        <div class="col-md-12">
                                <div class="form-group">
                                        <label>Post-nom</label>
                                        {% if form.post_nom.errors %}
                                        {{ form.post_nom(class="form-control border-input is-invalid")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.post_nom.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.post_nom(class="form-control border-input")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                                </div>
            
                        </div>
                </div>

                <div class="row">
                        <div class="col-md-12">
                                <div class="form-group">
                                        <label>Fonction</label>
                                        {% if form.role.errors %}
                                        {{ form.role(class="form-control select2 ")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.role.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.role(class="form-control select2")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                                </div>
            
                        </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>E-mail</label>
                                    {% if form.username.errors %}
                                    {{ form.username(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.username.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.username(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Mot de passe</label>
                                    {% if form.password.errors %}
                                    {{ form.password(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.password(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="text-center">
                        <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-user"></i> Ajouter administrateur
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/user/ajuser.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Ajouter utilisateur</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
                <div class="row">
                    <div class="col-md-4">
                            <div class="form-group">
                                    <label>Prénom</label>
                                    {% if form.prenom.errors %}
                                    {{ form.prenom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.prenom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.prenom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
                    <div class="col-md-8">
                            <div class="form-group">
                                    <label>Nom </label>
                                    {% if form.nom.errors %}
                                    {{ form.nom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.nom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.nom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="row">
                        <div class="col-md-12">
                                <div class="form-group">
                                        <label>Post-nom</label>
                                        {% if form.post_nom.errors %}
                                        {{ form.post_nom(class="form-control border-input is-invalid")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.post_nom.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.post_nom(class="form-control border-input")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                                </div>
            
                        </div>
                </div>

                <div class="row">
                        <div class="col-md-12">
                                <div class="form-group">
                                        <label>Fonction</label>
                                        {% if form.role.errors %}
                                        {{ form.role(class="form-control select2 ")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.role.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.role(class="form-control select2")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                                </div>
            
                        </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>E-mail</label>
                                    {% if form.username.errors %}
                                    {{ form.username(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.username.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.username(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Mot de passe</label>
                                    {% if form.password.errors %}
                                    {{ form.password(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.password(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="text-center">
                        <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-user"></i> Nouvel utilisateur
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/user/password.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Modification mot de passe ({{ user_nom}})</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
                <div class="row">
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Mot de passe </label>
                                    {% if form.password.errors %}
                                    {{ form.password(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.password(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                    <label>Confirmer mot de passe</label>
                                    {% if form.confirm_password.errors %}
                                    {{ form.confirm_password(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.confirm_password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.confirm_password(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
                    </div>
                </div>

                <div class="text-center">
                        <button class="btn btn-outline-warning btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-pencil-alt"></i> Modifier mot de passe
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/user/views.html
{% extends "base.html" %}

{% block body %}

<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 80px 30px  80px">
            
        <div class="header">
            <h4 class="title">Les utilisateurs</h4>
            <p class="category">Les droits d'acces dépend de la fonction.</p>

            <a href="{{ url_for('user.ajuser')}}" class="btn btn-warning"> <i class="ti-user"></i> Ajouter utilisateur </a>

        </div>

       
        {% with messages= get_flashed_messages(with_categories=true) %}
            {% if messages  %}
                {% for category, message in messages %}
                    <div class="alert text-center alert-{{ category }}">
                        <b>{{ message }}</b>
                    </div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">

                <thead>
                    <th>Noms</th>
                    <th>E-mail</th>
                    <th class="text-center">Mot de passe</th>
                    <th  class="text-center">Fonction</th>
                    <th  class="text-center">Statut</th>
                    <th  class="text-center">Action</th>
                </tr></thead>
                <tbody>
                    {% for listes in liste%}
                        <tr>
                            <td> {{ ' {} {} {} '.format(listes.nom, listes.post_nom, listes.prenom)  }} </td>
                            <td> {{ listes.username }} </td>
                            <td class="text-center"> <a href="{{ url_for('user.passuser', user_id=listes.id)}}">************ <i class="ti-pencil-alt"></i></a> </td>
                            <td  class="text-center"> {{ listes.role}} </td>
                            {% if listes.statut==True%}
                            <td  class="text-center"><a href="{{ url_for('user.statutuser', user_id=listes.id)}}  " class="btn btn-success"> <i class="ti-unlock"></i> </a></td>
                            {% else %}
                            <td  class="text-center"><a href="{{ url_for('user.statutuser', user_id=listes.id)}}" class="btn btn-danger"> <i class="ti-lock"></i> </a></td>
                            {% endif%}
                            <td  class="text-center"> <a href="{{ url_for('user.edituser', user_id=listes.id)}}" class="btn btn-warning"> <i class="ti-pencil-alt"></i> </a> </td>
                        </tr>
                    {% endfor %}
 
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock body %}