app/categorie/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length,Email, EqualTo, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import Types

def rech_type():
    return Types.query.all()

class AjoutCatForm(FlaskForm):
    nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    rech_type= QuerySelectField(query_factory=rech_type, get_label='nom', allow_blank=False)
    submit = SubmitField('Categorie')

    #Fornction de verification d'unique existenace dans la base des données
    def validate_nom(self, nom):
        type= Types.query.filter_by(nom=nom.data).first()
        if type:
            raise ValidationError("Cette catégorie existe déjà")

class EditCatForm(FlaskForm):
    ed_nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    ed_rech_type= QuerySelectField(query_factory=rech_type, get_label='nom', allow_blank=False)
    ed_submit = SubmitField('Classification')

    #Fornction de verification d'unique existenace dans la base des données
    def validate_ed_nom(self, ed_nom):
        type= Types.query.filter_by(nom=ed_nom.data).first()
        if type:
            raise ValidationError("Cette classification existe déjà")

app/categorie/__init__.py
from flask import Blueprint

categorie = Blueprint('categorie', __name__, url_prefix='/categorisation')
# never forget 
from . import routes

app/categorie/routes.py
from flask import render_template, flash, url_for, redirect, request, session
from .. import db, bcrypt
from ..models import Types, Categorie
from app.categorie.forms import AjoutCatForm, EditCatForm
from flask_login import login_user, current_user, logout_user, login_required
from . import categorie



''' Ajoute une categorisation '''

@categorie.route('/ajou_categorie', methods=['GET', 'POST'])
@login_required
def ajoutcate():

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Titre
   title='Categorisation | Kivu Exchange'
   #formulaire
   form=AjoutCatForm()

   if form.validate_on_submit():
      nom_cat=form.nom.data.capitalize()
      #Requete de verification de la catégorie
      req_ver=Categorie.query.filter_by(nom=nom_cat).first()

      if req_ver:
         if req_ver.type_id == form.rech_type.data.id:
            flash("Cette categorisation existe avec cette classification",'success')
            return redirect(url_for('categorie.ajoutcate')) 
      categorie_enre=Categorie(nom=nom_cat, type_id=form.rech_type.data.id)
      db.session.add(categorie_enre)
      db.session.commit()
      flash("Ajout avec succès une nouvelle categorisation",'success')
      return redirect(url_for('categorie.litcate')) 

   return render_template('categorie/ajouter.html',  title=title, form=form)

""" Liste des types """

@categorie.route('/lis_categorie', methods=['GET', 'POST'])
@login_required
def litcate():
   
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Titre
   title='Categorisation | Kivu Exchange'
   #Requête d'affichage de la categorisation
   listes=Categorie.query.order_by(Categorie.id.desc())

   return render_template('categorie/views.html',title=title, liste=listes)

""" Modifier statut de l'Utilisateur """

@categorie.route('/statut_cate/<int:cat_id>', methods=['GET', 'POST'])
@login_required
def statutcat(cat_id):
   #Titre
   title='Categorisation | Kivu Exchange'

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Requête de vérification de la categorie
   cat_statu=Categorie.query.filter_by(id=cat_id).first()

   if cat_statu is None:
      return redirect(url_for('categorie.litcate'))

   if cat_statu.statut == True:
      cat_statu.statut=False
      db.session.commit()
      flash("La catégorie est désactivée sur la plateforme",'success')
      return redirect(url_for('categorie.litcate'))
   else:
      cat_statu.statut=True
      db.session.commit()
      flash("La catégorie est activée sur la plateforme",'success')
      return redirect(url_for('categorie.litcate'))
   
   return render_template('user/views.html',title=title)


""" Modification de la catégorie  """

@categorie.route('/edit_<int:cate_id>_cate', methods=['GET', 'POST'])
@login_required
def editcate(cate_id):
       
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))       
   
   form=EditCatForm()
   #Titre
   title='Catégorisation | Kivu Exchange'
   #Requête de vérification du type
   cate_class=Categorie.query.filter_by(id=cate_id).first()
   #Le nom du type encours de modification
   cate_nom=cate_class.nom

   if cate_class is None:
      return redirect(url_for('categorie.litcate'))
   
   if form.validate_on_submit(): 
      cate_class.nom=form.ed_nom.data.capitalize()
      cate_class.type_id=form.ed_rech_type.data.id
      db.session.commit()
      flash("Modification réussie",'success')
      return redirect(url_for('categorie.litcate'))
      
   if request.method=='GET':
      form.ed_nom.data=cate_class.nom
      form.ed_rech_type.data=cate_class.type_categorie.nom

   return render_template('categorie/editcat.html', form=form, title=title, cate_nom=cate_nom)

app/templates/categorie/ajouter.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Ajouter une catégorie</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}

                <div class="row">
                        <div class="col-md-12">
                                <div class="form-group">
                                        <label>Nom de la catégorie</label>
                                        {% if form.nom.errors %}
                                        {{ form.nom(class="form-control border-input is-invalid")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.nom.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.nom(class="form-control border-input")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                                </div>
            
                        </div>
                </div>

                <div class="row">
                        <div class="col-md-12">
                                <div class="form-group">
                                        <label>Classification </label>
                                        {% if form.rech_type.errors %}
                                        {{ form.rech_type(class="form-control select2 ")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.rech_type.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.rech_type(class="form-control select2")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                                </div>
            
                        </div>
                </div>

                <div class="text-center">
                        <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-layout-column2-alt"></i> Nouvelle catégorie
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/categorie/editcat.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Editer ({{ cate_nom }})  </h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
                
                <div class="row">
                    <div class="col-md-12">
                            <div class="form-group">
                                    <label>Nom de la catégorie</label>
                                    {% if form.ed_nom.errors %}
                                    {{ form.ed_nom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_nom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_nom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
            </div>

            <div class="row">
                    <div class="col-md-12">
                            <div class="form-group">
                                    <label>Classification </label>
                                    {% if form.ed_rech_type.errors %}
                                    {{ form.ed_rech_type(class="form-control select2 ")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_rech_type.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_rech_type(class="form-control select2")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
            </div>

            <div class="text-center">
                    <button class="btn btn-outline-info btn-md" id="submit" name="ed_submit" type="submit">
                            <i class="ti-layout-column2-alt"></i> Editer catégorie
                    </button>
            </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/categorie/views.html
{% extends "base.html" %}

{% block body %}

<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 80px 30px  80px">
            
        <div class="header">
            <h4 class="title">Les catégories </h4>
            <br>
            <a href="{{ url_for('categorie.ajoutcate')}}" class="btn btn-success"> <i class="ti-menu-alt"></i> Ajouter une catégorie </a>

        </div>

       <br>
        {% with messages= get_flashed_messages(with_categories=true) %}
            {% if messages  %}
                {% for category, message in messages %}
                    <div class="alert text-center alert-{{ category }}">
                        <b>{{ message }}</b>
                    </div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">

                <thead>
                    <th>Noms</th>
                    <th class="text-center">Classification</th>
                    <th  class="text-center">Statut</th>
                    <th  class="text-center">Action</th>
                </tr></thead>
                <tbody>
                    {% for listes in liste%}
                        <tr>
                            <td> {{ ' {} {} {} '.format(listes.nom, listes.post_nom, listes.prenom)  }} </td>
                            <td class="text-center"> {{ listes.type_categorie.nom }} </td>
                            {% if listes.statut==True%}
                            <td  class="text-center"><a href="{{ url_for('categorie.statutcat', cat_id=listes.id)}}  " class="btn btn-success"> <i class="ti-unlock"></i> </a></td>
                            {% else %}
                            <td  class="text-center"><a href="{{ url_for('categorie.statutcat', cat_id=listes.id)}} " class="btn btn-danger"> <i class="ti-lock"></i> </a></td>
                            {% endif%}
                            <td  class="text-center"> <a href="{{ url_for('categorie.editcate', cate_id=listes.id)}}" class="btn btn-warning"> <i class="ti-pencil-alt"></i> </a> </td>
                        </tr>
                    {% endfor %}
 
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock body %}