app/trucking/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField, DecimalField, DateTimeField
from wtforms.validators import DataRequired, Length,Email, EqualTo, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField
#from wtforms_components import CountryField

from ..models import Transit, Trucking


class AjouTrucking(FlaskForm):
    provenance= StringField('Provenance', validators=[DataRequired("Completer la ville")])
    destination=StringField('Provenance', validators=[DataRequired("Completer la ville")])
    date_envoi=DateTimeField('Date', format='%Y-%m-%d %H:%M:%S', validators=[DataRequired("Completer la date")])
    ville= StringField('Ville', validators=[DataRequired("Completer la ville")])
    submit = SubmitField('Trucking number')

class Datelivraison(FlaskForm):
    date_livraison=DateTimeField('Date', format='%Y-%m-%d %H:%M:%S', validators=[DataRequired("Completer la date")])
    submit = SubmitField('Trucking number')

class TransitTrucking(FlaskForm):
    en_transit=StringField('Provenance', validators=[DataRequired("Completer la ville")])
    ville= StringField('Ville', validators=[DataRequired("Completer la ville")])
    resume= TextAreaField(validators=[DataRequired("Commentaire ")])
    date_envoi=DateTimeField('Date', format='%Y-%m-%d %H:%M:%S', validators=[DataRequired("Completer la date")])
    submit = SubmitField('Trucking number')

class TransitModTrucking(FlaskForm):
    truckingnumber= StringField('Provenance', validators=[DataRequired("Completer la ville")])
    en_transit=StringField('Provenance', validators=[DataRequired("Completer la ville")])
    ville= StringField('Ville', validators=[DataRequired("Completer la ville")])
    resume= TextAreaField(validators=[DataRequired("Commentaire ")])
    submit = SubmitField('Trucking number')


class MofTrucking(FlaskForm):
    truckingnumber= StringField('Provenance', validators=[DataRequired("Completer la ville")])
    provenance= StringField('Provenance', validators=[DataRequired("Completer la ville")])
    destination=StringField('Destination', validators=[DataRequired("Completer la ville")])
    ville= StringField('Ville', validators=[DataRequired("Completer la ville")])
    submit = SubmitField('Trucking number')

app/trucking/__init__.py
from flask import Blueprint

trucking = Blueprint('trucking', __name__, url_prefix='/trucking')
# never forget 
from . import routes

app/trucking/routes.py
from flask import render_template, flash, url_for, redirect, request, session
from .. import db, bcrypt
from ..models import Trucking, Transit
from app.trucking.forms import AjouTrucking, TransitTrucking, Datelivraison, MofTrucking, TransitModTrucking
from app.trucking.utiliescode import trucking_number, truckin_id
from flask_login import login_user, current_user, logout_user, login_required

from . import trucking



''' Ajoute un numero de trucking number '''

@trucking.route('/ajoutrucking', methods=['GET', 'POST'])
@login_required
def ajouttucking():

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Titre
   title='Trucking | Kivu Exchange'
   #formulaire

   form=AjouTrucking()
   #Code de tracking number unique
   code_tracking=None
   #Verification de l'existe dans la base des données des informations sur Trucking number
   compteur=0
   while compteur < 1: 
      truck=code_trente_min=Trucking.query.filter_by(tracking_number=trucking_number()).first()
      if truck is None:
         code_tracking=trucking_number()
         break
      else:
         pass
      compteur +=1

   if form.validate_on_submit():
      nv_truck=Trucking(tracking_number=code_tracking,ville_provenance=form.ville.data.capitalize(),
                        provenance=form.provenance.data,
                        destination=form.destination.data,
                        date_envoi=form.date_envoi.data)
      db.session.add(nv_truck)
      db.session.commit()
      session['truck']=nv_truck.id
      return redirect(url_for('trucking.littruck'))

   return render_template('trucking/ajouter.html',  title=title, form=form)


""" Liste des types """

@trucking.route('/lis_colis', methods=['GET', 'POST'])
@login_required
def littruck():
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))
   #Titre
   title='Trucking number | Kivu Exchange'
   #Requête d'affichage des trucking number
   listes=Trucking.query.order_by(Trucking.id.desc())
   return render_template('trucking/views.html',title=title, liste=listes)

""" Ajouter d'une transit """

@trucking.route('/transit_<int:transit_id>_colis', methods=['GET', 'POST'])
@login_required
def ajoutransit(transit_id):
       
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))       
   
   form=TransitTrucking()
   #Titre
   title='Transit | Kivu Exchange'
   #Requête de vérification du tracking
   truking_req=Trucking.query.filter_by(id=transit_id).first_or_404()
   #Le nom du type encours de modification
   cate_nom=truking_req.tracking_number
   #Verification de l'existence tracking number
   if truking_req is None:
      return redirect(url_for('trucking.littruck'))
   
   if form.validate_on_submit(): 
      transit=Transit(en_transit=form.en_transit.data, ville_transit=form.ville.data, 
                        date_envoi_transit=form.date_envoi.data, resume=form.resume.data, trucking_id=transit_id)
      db.session.add(transit)
      db.session.commit()
      return redirect(url_for('trucking.littruck'))

   return render_template('trucking/transit.html', form=form, title=title, cate_nom=cate_nom)


""" Livraison du colis"""

@trucking.route('/statut_transit/<int:transit_id>', methods=['GET', 'POST'])
@login_required
def statutranist(transit_id):
   #Titre
   title='Statut Tracking | Kivu Exchange'

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Requête de vérification du trancking
   track_statu=Trucking.query.filter_by(id=transit_id).first_or_404()

   if track_statu is None:
      return redirect(url_for('trucking.littruck'))

   if track_statu.statut == True:
      track_statu.statut=False
      db.session.commit()
      flash("Le colis recommence la route",'success')
      return redirect(url_for('trucking.datelivraison', transit_id=transit_id))
   else:
      track_statu.statut=True
      db.session.commit()
      flash("Le colis est livré",'success')
      return redirect(url_for('trucking.datelivraison', transit_id=transit_id))
   
   return render_template('user/views.html',title=title)

@trucking.route('/date_livraison/<int:transit_id>', methods=['GET', 'POST'])
@login_required
def datelivraison(transit_id):
   #Titre
   title='Livarsion colis | Kivu Exchange'

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Requête de vérification du trancking
   track_statu=Trucking.query.filter_by(id=transit_id).first_or_404()

   if track_statu is None:
      return redirect(url_for('trucking.littruck'))

   form=Datelivraison()

   if form.validate_on_submit():
      if track_statu.date_livraison is None and track_statu.statut==True :
         track_statu.date_livraison=form.date_livraison.data
         db.session.commit()
         flash("Le colis est livré", "success")
         return redirect(url_for('trucking.littruck'))
   
   num_track=track_statu.tracking_number
   
   return render_template('trucking/date.html',title=title, truck=num_track, form=form)


@trucking.route('/borderau/<int:transit_id>', methods=['GET', 'POST'])
@login_required
def bordtransit(transit_id):
   #Titre
   title='Bordereaux | Kivu Exchange'

   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))

   #Requête de vérification du trancking
   track_statu=Trucking.query.filter_by(id=transit_id).first_or_404()
   #Transit du colis.
   track_transit=Transit.query.filter_by(trucking_id=track_statu.id).all()

   if track_statu is None:
      return redirect(url_for('trucking.littruck'))

   return render_template('trucking/document.html',title=title, truck=track_statu, track_transit=track_transit)


""" Modification du trucking  """

@trucking.route('/truckind_<int:transit_id>.kivu', methods=['GET', 'POST'])
@login_required
def trackdocmod(transit_id):
       
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))       
   
   form=MofTrucking()
   #Titre
   title='Modifier bordeaux | Kivu Exchange'
   #Requête de vérification du trancking
   track_statu=Trucking.query.filter_by(id=transit_id).first_or_404()
   #Le nom du type encours de modification
   trucking_number_form=track_statu.tracking_number

   if track_statu is None:
      return redirect(url_for('trucking.littruck'))
   
   if form.validate_on_submit():
      track_statu.provenance=form.provenance.data
      track_statu.destination=form.destination.data
      track_statu.ville_provenance=form.ville.data
      db.session.commit()
      flash("Modification réussie",'success')
      return redirect(url_for('trucking.littruck'))
      
   if request.method=='GET':
      form.provenance.data=track_statu.provenance
      form.destination.data=track_statu.destination
      form.ville.data=track_statu.ville_provenance
      form.truckingnumber.data=trucking_number_form

   return render_template('trucking/modform.html', form=form, title=title)



@trucking.route('/trucktranist_<int:transit_id>.kivu', methods=['GET', 'POST'])
@login_required
def tracktransit(transit_id):
       
   #La modification du mot de passe par l'administrateur.
   if current_user.role!='Admin':
      return redirect(url_for('main.dashboard'))       
   
   form=TransitModTrucking()
   #Titre
   title='Modifier bordeaux | Kivu Exchange'
   #Requête de vérification du trancking
   track_statu=Transit.query.filter_by(trucking_id=transit_id).first_or_404()


   if track_statu is None:
      return redirect(url_for('trucking.littruck'))
   
   if form.validate_on_submit():
      track_statu.en_transit=form.en_transit.data
      track_statu.ville_transit=form.ville.data
      track_statu.resume=form.resume.data
      db.session.commit()
      flash("Modification réussie",'success')
      return redirect(url_for('trucking.littruck'))
      
   if request.method=='GET':
      form.en_transit.data=track_statu.en_transit
      form.ville.data=track_statu.ville_transit
      form.resume.data=track_statu.resume
      form.truckingnumber.data=track_statu.trucking_transit.tracking_number

   return render_template('trucking/modtransit.html', form=form, title=title)

app/templates/trucking/ajouter.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin-top: 100px; margin-bottom: 150px; ">
        <div class="header">
            <h4 class="title">Ajouter un colis</h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}

                <div class="row">
                        <div class="col-md-6">
                                <div class="form-group">
                                        <label>Pays de provenance</label>
                                        {% if form.provenance.errors %}
                                        {{ form.provenance(class="form-control border-input is-invalid")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.provenance.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.provenance(class="form-control border-input")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                                </div>
            
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                    <label>Ville de Provenance</label>
                                    {% if form.ville.errors %}
                                    {{ form.ville(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ville.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ville(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                            <div class="form-group">
                                    <label>Pays de destination</label>
                                    {% if form.destination.errors %}
                                    {{ form.destination(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.destination.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.destination(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                                <label>Date d'envoie</label>
                                {% if form.date_envoi.errors %}
                                {{ form.date_envoi(class="form-control border-input is-invalid")}}
                                <i class="form-group__bar"></i>
                                <div class="invalid-feedback">
                                    {% for error in form.date_envoi.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.date_envoi(class="form-control border-input")}}
                                <i class="form-group__bar"></i>
                                {% endif %}
                        </div>
    
                </div>
            </div>

                
                <div class="text-center">
                        <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-layout-column2-alt"></i> Nouveau colis
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/trucking/date.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin-top: 100px; margin-bottom: 150px; ">
        <div class="header">
            <h4 class="title">Livraison colis (N°:{{truck}}) </h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}


                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                                <label>Date de livraison</label>
                                {% if form.date_livraison.errors %}
                                {{ form.date_livraison(class="form-control border-input is-invalid")}}
                                <i class="form-group__bar"></i>
                                <div class="invalid-feedback">
                                    {% for error in form.date_livraison.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.date_livraison(class="form-control border-input")}}
                                <i class="form-group__bar"></i>
                                {% endif %}
                        </div>
    
                    </div>
                </div>

                
                <div class="text-center">
                        <button class="btn btn-outline-info btn-md" id="submit" name="submit" type="submit">
                                <i class="ti-truck"></i> Date de livraison
                        </button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/trucking/document.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin-top: 40px; margin-bottom: 150px; ">
        <div class="header">
            <div class="content table-responsive table-full-width">
            <div class="row">
               <div class="col-md-4">
                <img src=" {{url_for('static', filename='logo/t.png')}} " alt="">
               </div>
               <div class="col-md-6">
                <h4 class="title text-center">BORDEREAUX D'EXPEDITION </h4>
            </div> 
            </div>
            
            <table class="table table-striped">
            <tbody>

                <tr>
                    <td>Numéro de suivi: </td>
                    <td>  <a href="  {{ url_for('trucking.trackdocmod', transit_id=truck.id)}} "> <b>{{truck.tracking_number }}</b></a></td>
                    <td> </td>
                    <td> 
                        {% if truck.date_livraison == None and truck.statut== 0 %}
                        <a class="btn btn-sm btn-danger">  <i class="ti-truck"></i>  </a>
                        {% else %}
                        <a class="btn btn-sm btn-success">  <i class="ti-check"></i>  </a>
                        {% endif %}
                    
                    </td>
                </tr>

                <tr>
                    <td>Provenance: </td>
                    <td>{{truck.provenance }} ({{truck.ville_provenance}}): </td>
                    <td>Jour et date d'envoi: </td>
                    <td> {{truck.date_envoi.strftime('%d/%m/%Y %H:%M:%S')}}  </td>
                </tr>

                <tr>
                    <td>Destination: </td>
                    <td>{{truck.destination }} </td>
                    <td>Jour et date livraison: </td>
                    <td> 
                      {% if truck.date_livraison == None and truck.statut== 0 %}  
                        En transit
                      {% else %}  
                        {{truck.date_livraison.strftime('%d/%m/%Y %H:%M:%S')}} 
                      {% endif %}
                    </td>
                </tr>
            </tbody>
            </table>

            <br><h4>Transit</h4>

            <table class="table table-striped">
                <tbody>


                {% for transit in track_transit %}
                    <tr>
                        <td> <a href="{{ url_for('trucking.tracktransit', transit_id=truck.id)}}">{{ transit.en_transit }} ({{transit.ville_transit}})</a>  </td>
                        <td> {{ transit.date_envoi_transit.strftime('%d/%m/%Y %H:%M:%S') }} </td>
                        <td> <p class="text-justify">
                            {{ transit.resume }}
                        </p> </td>       
                    </tr>
                {% endfor %}
                    
    

                </tbody>
                </table>
            </div>
            
        </div>
        <div class="content">
                
        </div>
    </div>
</div>

{% endblock body %}

app/templates/trucking/editcat.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp" style="margin: 30px 150px 30px  150px">
        <div class="header">
            <h4 class="title">Editer ({{ cate_nom }})  </h4>
        </div>
        <div class="content">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

            <form method="POST" enctype="multipart/form-data" >
                {{ form.csrf_token }}
                
                <div class="row">
                    <div class="col-md-12">
                            <div class="form-group">
                                    <label>Nom de la catégorie</label>
                                    {% if form.ed_nom.errors %}
                                    {{ form.ed_nom(class="form-control border-input is-invalid")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_nom.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_nom(class="form-control border-input")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
            </div>

            <div class="row">
                    <div class="col-md-12">
                            <div class="form-group">
                                    <label>Classification </label>
                                    {% if form.ed_rech_type.errors %}
                                    {{ form.ed_rech_type(class="form-control select2 ")}}
                                    <i class="form-group__bar"></i>
                                    <div class="invalid-feedback">
                                        {% for error in form.ed_rech_type.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.ed_rech_type(class="form-control select2")}}
                                    <i class="form-group__bar"></i>
                                    {% endif %}
                            </div>
        
                    </div>
            </div>

            <div class="text-center">
                    <button class="btn btn-outline-info btn-md" id="submit" name="ed_submit" type="submit">
                            <i class="ti-layout-column2-alt"></i> Editer catégorie
                    </button>
            </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

app/templates/trucking/views.html
{% extends "base.html" %}

{% block body %}

<div class="col-lg-12 col-md-12">
    <div class="card box-shadow--4dp">
            
        <div class="header">
            <h4 class="title">Suivi des colis </h4>
            <br>
            <a href="{{ url_for('trucking.ajouttucking')}}" class="btn btn-warning"> <i class="ti-truck"></i> Ajouter un colis </a>
        </div>

       <br>
        {% with messages= get_flashed_messages(with_categories=true) %}
            {% if messages  %}
                {% for category, message in messages %}
                    <div class="alert text-center alert-{{ category }}">
                        <b>{{ message }}</b>
                    </div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">

                <thead>
                    <th>Trucking number</th>
                    <th class="text-center">Pays(Ville) de pro.</th>
                    <th  class="text-center">Pays de dest.</th>
                    <th  class="text-center">Date d'envoi.</th>
                    <th  class="text-center">Date reception.</th>
                    <th  class="text-center">Transit(ajouter)</th>
                    <th  class="text-center">Livraison</th>
                    <th  class="text-center">Apercu</th>
                </tr></thead>
                <tbody>
                    {% for listes in liste%}
                        <tr>
                            <td> {{ listes.tracking_number }} </td>
                            <td> {{ ' {} ({}) '.format(listes.provenance,listes.ville_provenance ) }} </td>
                            <td> {{ listes.destination }} </td>
                            <td> {{ "{} à {} ".format(listes.date_envoi.strftime('%d/%m/%Y'),listes.date_envoi.strftime('%H:%M:%S') ) }} </td>
                            {% if listes.date_livraison==None %}
                            <td class="text-center"> <a class="btn btn-sm btn-danger">  <i class="ti-truck"></i>  </a></td>
                            {% else %}
                            <td> {{ listes.date_livraison.strftime('%d/%m/%Y %H:%M:%S') }} </td>
                            {% endif %}

                            {% if listes.statut == 0 and listes.date_livraison== None %}
                            <td  class="text-center"><a href="  {{ url_for('trucking.ajoutransit', transit_id=listes.id)}} " class="btn btn-danger"> <i class="ti-plus"></i> </a></td>
                            {% elif listes.statut == 1 and listes.date_livraison== None %}
                            <td  class="text-center"><a href="  {{ url_for('trucking.datelivraison', transit_id=listes.id)}} " class="btn btn-danger"> Completer date </a></td>
                            {% else %}
                            <td class="text-center"> <a class="btn btn-sm btn-success"><i  class="ti-check"></i></a> </td>
                            {% endif %}
                            
                            {% if listes.statut == 0 %}
                            <td  class="text-center"><a href=" {{ url_for('trucking.statutranist', transit_id=listes.id)}}" class="btn btn-danger"> <i class="ti-unlock"></i> </a></td>
                            {% else %}
                            <td  class="text-center"><a href="{{ url_for('trucking.statutranist', transit_id=listes.id)}}" class="btn btn-info"> <i class="ti-lock"></i> </a></td>
                            {% endif %}

                            <td class="text-center"> <a href="{{ url_for('trucking.bordtransit', transit_id=listes.id)}}" class="btn btn-warning"> <i class="ti-agenda"></i> </a> </td>

                        
                        </tr>
                    {% endfor %}
 
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock body %}